first_names_male = ['boys', 'an', 'bing', 'chen', 'chung', 'confucius', 'cong', 'deshi', 'dewei', 'fo-hai', 'fo-hsing',
                    'gan', 'gao', 'genjo', 'ho', 'hsin', 'huang fu', 'hui-chao', "huik'o", 'jiang', 'jin', 'jing',
                    'jun', 'kong', 'lao-tzu', 'lee', 'lei', 'li', 'li-liang', 'liang', 'liko', 'manchu', 'ming',
                    'niao-ka', 'on', 'qing-nan', 'quon', 'shen', 'shing', 'sun', 'tung', 'uang', 'wang', 'wen', 'woo',
                    'wu-pen', 'xi-wang', 'xiaoping', 'xin', 'xing-fu', 'yao', 'ye', 'yo', 'yong', 'yu', 'yuan', 'zhong',
                    'zhu', 'zhuang']

first_names_female = ['ah lam', 'an', 'bao', 'chen', 'chen-chio', 'chen-tao', 'chow', 'chu hua', 'chun', 'chyou',
                      'da-shin', 'da-xia', 'fai', 'fang', 'fang hua', 'genji', 'guanyin', 'hua', 'hui fang', 'jing wei',
                      'jun', 'kimora', 'le', 'lee', 'lei', 'li', 'li hua', 'li mei', 'li ming', 'lian', 'lien', 'lin',
                      'ling', 'lixue', 'mee', 'mei', 'mingmei', 'quan', 'shu fang', 'ting', 'ushi', 'xiang',
                      'xiao-niao', 'xiao-xing', 'xin', 'xiu mei', 'yin', 'yu', 'zan', 'zhengqiu', 'zhi', 'zhijuan',
                      'zi']

last_names = ['an', 'ang', 'ang', 'ao', 'au', 'au yeung', 'ba', 'bai', 'bai', 'ban', 'bao', 'bao', 'bao', 'bao', 'bau',
              'bau', 'bau', 'bi', 'bo', 'bo', 'bu', 'bu', 'cai', 'cao', 'cha', 'chai', 'cham', 'chan', 'chan', 'chang',
              'chang', 'chang', 'chang', 'chao', 'chao', 'chao', 'chao', 'chau', 'chau', 'chau', 'chau', 'che', 'che',
              'cheah', 'chee', 'chen', 'cheng', 'cheng', 'cheng', 'cheong', 'cheong', 'chern', 'cheung', 'cheung',
              'cheung', 'chew', 'chi', 'chi', 'chi', 'chi', 'chi', 'chi', 'chi', 'chi', 'chi', 'chi', 'chi', 'chi',
              'chi', 'chia', 'chiang', 'chiang', 'chiang', 'chiao', 'chiao', 'chien', 'chien', 'chim', 'chin', 'chin',
              'chin', 'chin', 'chin', 'chin', 'ching', 'ching', 'ching', 'ching', 'ching', 'chiong', 'chiong', 'chiou',
              'chiou', 'chiou', 'chiou', 'chiu', 'chiu', 'chiu', 'chiu', 'chiu', 'cho', 'cho', 'choi', 'choi', 'chong',
              'chong', 'chong', 'chong', 'chong', 'choo', 'chou', 'chou', 'chou', 'chou', 'chow', 'chow', 'chow',
              'chow', 'choy', 'chu', 'chu', 'chu', 'chu', 'chu', 'chu', 'chu', 'chu', 'chu', 'chu', 'chua', 'chuang',
              'chui', 'chui', 'chun', 'chung', 'chung', 'chung', 'chung', 'cong', 'cui', 'dai', 'dang', 'dea', 'deng',
              'ding', 'do', 'dong', 'doo', 'du', 'du', 'duan', 'dung', 'eng', 'eng', 'fan', 'fan', 'fang', 'fang',
              'fei', 'feng', 'feng', 'feng', 'feng', 'fok', 'fong', 'fong', 'fong', 'foo', 'fu', 'fu', 'fu', 'fung',
              'fung', 'fung', 'fung', 'gan', 'gang', 'gao', 'gau', 'ge', 'ge', 'geng', 'go', 'go', 'goh', 'goh', 'gong',
              'gong', 'gong', 'gong', 'gong', 'gu', 'gu', 'gu', 'guan', 'guan', 'guo', 'guo', 'guo', 'ha', 'hai', 'han',
              'hang', 'hao', 'hau', 'hau', 'he', 'he', 'he', 'ho', 'hoh', 'hom', 'hon', 'hong', 'hong', 'hong', 'hong',
              'hoo', 'hou', 'hsi', 'hsia', 'hsiao', 'hsieh', 'hsieh', 'hsiung', 'hsu', 'hsu', 'hsueh', 'hu', 'hu',
              'hua', 'hua', 'hua', 'huang', 'hui', 'hui', 'huie', 'hum', 'hung', 'hung', 'hung', 'hung', 'huo', 'hwang',
              'hy', 'ing', 'ing', 'ip', 'jan', 'jang', 'jen', 'jeng', 'jeung', 'jeung', 'jew', 'jew', 'jia', 'jian',
              'jiang', 'jiang', 'jiang', 'jiao', 'jim', 'jin', 'jin', 'jin', 'jing', 'jing', 'jing', 'jing', 'jo',
              'joe', 'jong', 'joo', 'jou', 'jow', 'ju', 'ju', 'jue', 'jung', 'jung', 'kam', 'kam', 'kan', 'kan', 'kan',
              'kang', 'kang', 'kao', 'kau', 'ke', 'ke', 'keng', 'kho', 'khoo', 'kiang', 'king', 'king', 'ko', 'ko',
              'ko', 'ko', 'koh', 'kong', 'kong', 'kong', 'koo', 'koo', 'koo', 'kook', 'kou', 'kou', 'ku', 'ku', 'ku',
              'kuan', 'kuan', 'kuang', 'kuang', 'kuk', 'kung', 'kung', 'kuo', 'kwan', 'kwan', 'kwock', 'kwock', 'kwok',
              'kwok', 'kwon', 'kwon', 'kwong', 'kwong', 'lai', 'lai', 'lam', 'lam', 'lan', 'lang', 'lao', 'lao', 'lao',
              'lau', 'lau', 'lau', 'lee', 'lee', 'lee', 'lei', 'lei', 'leng', 'leong', 'leung', 'lew', 'li', 'li', 'li',
              'lian', 'lian', 'liang', 'liao', 'liaw', 'lien', 'lien', 'liew', 'lim', 'lin', 'lin', 'ling', 'liou',
              'liu', 'liu', 'liu', 'lo', 'lo', 'lo', 'loh', 'lok', 'lok', 'long', 'long', 'long', 'loo', 'lou', 'lou',
              'louie', 'louie', 'lu', 'lu', 'lu', 'lu', 'lu', 'lu', 'lua', 'lui', 'lui', 'luk', 'luk', 'lum', 'lum',
              'lung', 'lung', 'luo', 'luo', 'ma', 'mah', 'mai', 'mak', 'man', 'man', 'man', 'man', 'mao', 'mao', 'mar',
              'mau', 'may', 'mei', 'meng', 'meng', 'miao', 'miao', 'min', 'ming', 'miu', 'mo', 'mo', 'mo', 'mo', 'mok',
              'mon', 'mou', 'mou', 'moy', 'mu', 'mu', 'mui', 'na', 'ng', 'ng', 'ngai', 'ngai', 'ngan', 'ngo', 'ni',
              'nie', 'ning', 'niu', 'niu', 'on', 'ong', 'ou', 'ou yang', 'ow', 'owyang', 'pan', 'pang', 'pang', 'pang',
              'pao', 'pau', 'pei', 'pei', 'pei', 'peng', 'pi', 'pi', 'ping', 'po', 'po', 'pon', 'pong', 'pong', 'poon',
              'poon', 'pu', 'pu', 'pun', 'qi', 'qi', 'qi', 'qian', 'qiao', 'qin', 'qin', 'qiu', 'qiu', 'qiu', 'qiu',
              'qu', 'qu', 'qu', 'quan', 'quan', 'que', 'rao', 'ren', 'rong', 'rong', 'rong', 'tong', 'tong', 'tong',
              'tong', 'tong', 'tsai', 'tsai', 'tsang', 'tsang', 'tsao', 'tsay', 'tse', 'tseng', 'tso', 'tsoi', 'tsou',
              'tsu', 'tsui', 'tsui', 'tu', 'tu', 'tu', 'tuan', 'tung', 'tung', 'tung', 'tzeng', 'u', 'un', 'ung', 'wah',
              'wai', 'wai', 'wan', 'wan', 'wan', 'wang', 'wang', 'wee', 'wei', 'wei', 'wei', 'wen', 'wen', 'wen',
              'weng', 'wing', 'wong', 'wong', 'woo', 'woo', 'woo', 'woo', 'woo', 'woon', 'wu', 'wu', 'wu', 'wu', 'wu',
              'xi', 'xia', 'xiang', 'xiang', 'xiang', 'xiao', 'xiao', 'xie', 'xie', 'xin', 'xing', 'xiong', 'xu', 'xu',
              'xue', 'yam', 'yan', 'yan', 'yan', 'yan', 'yan', 'yan', 'yan', 'yan', 'yang', 'yang', 'yang', 'yao',
              'yap', 'yau', 'yau', 'yaw', 'yaw', 'ye', 'yee', 'yee', 'yee', 'yeh', 'yen', 'yen']

chinese = {
    'first_names_female': first_names_female,
    'first_names_male': first_names_male,
    'last_names': last_names
}