last_names = \
    ['chaudhari', 'chaudhary', 'chaudhry', 'chaudhuri', 'chaudry', 'chauhan', 'chawla', 'cheema', 'cherian',
     'chhabra', 'chokshi', 'chopra', 'choudhary', 'choudhry', 'choudhury', 'chowdhury', 'comar', 'contractor',
     'd’alia', 'dada', 'dalal', 'dani', 'dar', 'dara', 'dara', 'das', 'dasgupta', 'dash', 'dass', 'date',
     'datta', 'dave', 'dayal', 'de', 'deep', 'deo', 'deol', 'desai', 'deshmukh', 'deshpande', 'devan', 'devi',
     'dewan', 'dey', 'dhaliwal', 'dhar', 'dhar', 'dhawan', 'dhillon', 'dhingra', 'hayre', 'hegde', 'hora',
     'issac', 'iyengar', 'iyer', 'jaggi', 'jain', 'jani', 'jayaraman', 'jha', 'jhaveri', 'johal', 'joshi',
     'kadakia', 'kade', 'kakar', 'kala', 'kala', 'kala', 'kale', 'kalita', 'kalla', 'kamdar', 'kanda',
     'kannan', 'kant', 'kapadia', 'kapoor', 'kapur', 'kar', 'kara', 'karan', 'kari', 'karnik', 'karpe',
     'kashyap', 'kata', 'kaul', 'kaur', 'keer', 'keer', 'khalsa', 'khanna', 'khare', 'khatri', 'khosla',
     'khurana', 'kibe', 'kohli', 'mathai', 'mathur', 'matthai', 'meda', 'mehan', 'mehra', 'mehrotra', 'mehta',
     'meka', 'memon', 'menon', 'merchant', 'minhas', 'mishra', 'misra', 'mistry', 'mital', 'mitra', 'mittal',
     'mitter', 'modi', 'mody', 'mohan', 'mohanty', 'morar', 'more', 'mukherjee', 'mukhopadhyay', 'muni',
     'munshi', 'murthy', 'murty', 'mutti', 'nadig', 'nadkarni', 'nagar', 'nagarajan', 'nagi', 'nagy', 'naidu',
     'naik', 'nair', 'nanda', 'narain', 'narang', 'narasimhan', 'narayan', 'narayanan', 'narula', 'natarajan',
     'raj', 'raja', 'rajagopal', 'rajagopalan', 'rajan', 'raju', 'ram', 'rama', 'ramachandran', 'ramakrishnan',
     'raman', 'ramanathan', 'ramaswamy', 'ramesh', 'rana', 'randhawa', 'ranganathan', 'rao', 'rastogi',
     'ratta', 'rattan', 'ratti', 'rau', 'raval', 'ravel', 'ravi', 'ray', 'reddy', 'rege', 'rout', 'roy',
     'sabharwal', 'sachar', 'sachdev', 'sachdeva', 'sagar', 'saha', 'sahni', 'sahota', 'saini', 'salvi',
     'sama', 'sami', 'sampath', 'samra', 'sandal', 'sandhu', 'sane', 'sangha', 'sanghvi', 'srinivas',
     'srinivasan', 'srivastava', 'subramaniam', 'subramanian', 'sule', 'sundaram', 'sunder', 'sur', 'sura',
     'suresh', 'suri', 'swaminathan', 'swamy', 'tailor', 'tak', 'talwar', 'tandon', 'taneja', 'tank', 'tara',
     'tata', 'tella', 'thaker', 'thakkar', 'thakur', 'thaman', 'tiwari', 'toor', 'tripathi', 'trivedi',
     'upadhyay', 'uppal', 'vaidya', 'vala', 'varghese', 'varkey', 'varma', 'varty', 'varughese', 'vasa',
     'venkataraman', 'venkatesh', 'verma', 'vig', 'virk', 'viswanathan', 'vohra', 'vora', 'vyas']


first_names_male = \
    ['aamir', 'abbas', 'abdul', 'abhay', 'abhijeet', 'abhijit', 'abhilash', 'abhinav', 'abhishek',
     'abrar', 'adil', 'aditya', 'adnan', 'agni', 'ahmad', 'ahmed', 'ajay', 'ajeet', 'ajit', 'ajith',
     'akash', 'akbar', 'akhil', 'akshay', 'ali', 'amandeep', 'amar', 'amardeep', 'amarjeet', 'amin',
     'amir', 'amit', 'amitabh', 'amrit', 'anand', 'ananda', 'anant', 'ananth', 'anantha', 'anbu', 'anik',
     'aniket', 'anil', 'aniruddha', 'anish', 'anit', 'ankit', 'ankur', 'anoop', 'ansar', 'anuj', 'anup',
     'anupam', 'apoorva', 'apurva', 'arabinda', 'aravind', 'aravinda', 'arif', 'arijit', 'aritra',
     'arjun', 'arun', 'aruna', 'arya', 'aryan', 'asad', 'aseem', 'ashish', 'ashok', 'ashwin', 'asim',
     'aswathi', 'aurobindo', 'avinash', 'ayaan', 'ayan', 'ayaz', 'azad', 'azhar', 'aziz', 'babar',
     'baber', 'babur', 'bakhtiar', 'bala', 'balakrishna', 'baldev', 'balwinder', 'basant', 'basu',
     'bharat', 'bharath', 'bhaskar', 'bibek', 'bijay', 'bijoy', 'bilal', 'binay', 'bipin', 'bishal',
     'bishan', 'brijesh', 'chand', 'chanda', 'chandan', 'chander', 'chandra', 'chandrakant', 'chetan',
     'chiranjeevi', 'chiranjivi', 'damodar', 'danyal', 'darshan', 'dayaram', 'debdas', 'deep', 'deepak',
     'deo', 'dev', 'devadas', 'devaraj', 'devdas', 'devraj', 'dhananjay', 'dharma', 'dhaval', 'dileep',
     'dilip', 'dilshad', 'dinesh', 'dip', 'dipak', 'durai', 'durga', 'dushyant', 'ezhil', 'faisal',
     'fareed', 'farhan', 'farid', 'farrukh', 'ferdous', 'feroz', 'feroze', 'firdaus', 'firdos',
     'firdous', 'firoz', 'furqan', 'ganesh', 'gautam', 'geevarghese', 'ghulam', 'girish', 'gobind',
     'gobinda', 'gopal', 'gopinath', 'gotam', 'goutam', 'govind', 'govinda', 'gul', 'gulbahar',
     'gulshan', 'gulzar', 'gurdeep', 'gurmeet', 'gurpreet', 'haneef', 'hanif', 'hardeep', 'harendra',
     'hari', 'harinder', 'haris', 'harish', 'haroon', 'harpreet', 'harsh', 'harsha', 'harshad',
     'harshal', 'hasan', 'hassan', 'hira', 'imran', 'imtiaz', 'imtiyaz', 'inayat', 'inderjeet',
     'inderjit', 'inderpal', 'indra', 'indrajit', 'isha', 'jagadish', 'jagannath', 'jagdish', 'jagjit',
     'jahangir', 'jai', 'jaidev', 'jasvinder', 'jaswinder', 'javaid', 'javed', 'jay', 'jaya', 'jayadev',
     'jayant', 'jayanta', 'jayendra', 'jayesh', 'jaywant', 'jeetendra', 'jitender', 'jitendra', 'jothi',
     'jyothi', 'jyoti', 'kailash', 'kali', 'kalidas', 'kalyan', 'kalyana', 'kamal', 'kamala', 'kannan',
     'kanta', 'kanti', 'kapil', 'karan', 'karthik', 'karthikeyan', 'kartik', 'kavi', 'khan', 'khurshid',
     'kiran', 'kishan', 'kishor', 'kishore', 'krishna', 'kshitij', 'kuldeep', 'kumar', 'kumaran',
     'kunal', 'lakshman', 'lakshmi', 'lal', 'lalit', 'laxman', 'laxmi', 'lochan', 'lucky', 'madhav',
     'madhu', 'madhukar', 'madhur', 'mahavir', 'mahendra', 'mahesh', 'mahinder', 'mahmud', 'mamun',
     'manas', 'mandeep', 'mani', 'maninder', 'manish', 'manjeet', 'manoj', 'manpreet', 'manu', 'maqsood',
     'maqsud', 'maruf', 'masud', 'mayur', 'mehmood', 'mehmud', 'mitra', 'mitul', 'mohammad', 'mohammed',
     'mohan', 'mohandas', 'mohinder', 'muhammad', 'mukesh', 'mukul', 'mumtaz', 'murad', 'murali',
     'murtaza', 'murugan', 'nadeem', 'nadim', 'nagendra', 'nand', 'nanda', 'narayan', 'narayana',
     'narayanan', 'narendra', 'narinder', 'naseem', 'nasim', 'navdeep', 'naveen', 'navin', 'navneet',
     'neelam', 'neeraj', 'nihal', 'nikhil', 'nilam', 'ninad', 'niraj', 'nirav', 'nirmal', 'nishant',
     'nishat', 'nithin', 'nitin', 'nitya', 'noor', 'nur', 'om', 'padma', 'pallab', 'pallav', 'pankaj',
     'parminder', 'parth', 'partha', 'parveen', 'pitambar', 'prabhakar', 'prabhat', 'prabhu', 'prabodh',
     'pradeep', 'pradip', 'prakash', 'pramod', 'pran', 'pranav', 'pranay', 'prasad', 'prasanna',
     'prasenjit', 'prashant', 'prashanth', 'pratap', 'prateek', 'pratik', 'praveen', 'pravin', 'prem',
     'prosenjit', 'puneet', 'punit', 'purushottam', 'qasim', 'rabi', 'rabindra', 'radha', 'rafiq',
     'raghu', 'rahat', 'rahim', 'rahman', 'rahul', 'raj', 'raja', 'rajani', 'rajeev', 'rajender',
     'rajendra', 'rajesh', 'rajib', 'rajinder', 'rajiv', 'rajneesh', 'rajnish', 'raju', 'rakesh', 'ram',
     'rama', 'ramachandra', 'ramakrishna', 'ramesh', 'rameshwar']


first_names_female = \
    ['aarthi', 'aarti', 'abha', 'abhilasha', 'aditi', 'aisha', 'aishwarya', 'aiza', 'aizah',
     'akanksha', 'akhila', 'amala', 'amandeep', 'amardeep', 'amarjeet', 'amita', 'amrita', 'anandi',
     'anika', 'anila', 'anima', 'anisha', 'anita', 'anjali', 'ankita', 'anuja', 'anupama', 'aparajita',
     'aparna', 'apoorva', 'apurva', 'aradhana', 'arati', 'archana', 'arti', 'aruna', 'arundhati',
     'arushi', 'arya', 'asha', 'avani', 'avanti', 'ayesha', 'azra', 'bala', 'balwinder', 'bhavana',
     'bhavna', 'bushra', 'chanda', 'chandana', 'chandra', 'chandrakanta', 'chetana', 'darshana',
     'deepa', 'deepali', 'deepika', 'deepti', 'devi', 'devika', 'diksha', 'dilshad', 'dipa', 'dipali',
     'dipika', 'dipti', 'disha', 'divya', 'diya', 'drishti', 'durga', 'esha', 'ezhil', 'fahmida',
     'fareeha', 'farhana', 'fariha', 'fatima', 'ferdous', 'ferdousi', 'gargi', 'gauhar', 'gauri',
     'gayathri', 'gayatri', 'gita', 'gowri', 'grishma', 'gul', 'gulbadan', 'gulbahar', 'gulnaz',
     'gulrukh', 'gulzar', 'gurdeep', 'gurmeet', 'gurpreet', 'harinder', 'harpreet', 'harshada', 'hema',
     'hira', 'humaira', 'ila', 'inaaya', 'inaya', 'inderjeet', 'inderjit', 'inderpal', 'indira',
     'indrani', 'indu', 'indumathi', 'iqra', 'isha', 'ishani', 'ishita', 'jahanara', 'jannat',
     'jannatulferdous', 'jasvinder', 'jaswinder', 'jaya', 'jayanthi', 'jayanti', 'jayashri', 'jothi',
     'jyothi', 'jyoti', 'jyotsana', 'jyotsna', 'kajal', 'kala', 'kali', 'kalpana', 'kalyani',
     'kamakshi', 'kamala', 'kamatchi', 'kamini', 'kanchana', 'kanta', 'kanti', 'karishma', 'karthika',
     'kashi', 'kasi', 'kaur', 'kaveri', 'kavita', 'kavitha', 'khurshid', 'khushi', 'kiran', 'kirtida',
     'kishori', 'kshitija', 'kumari', 'laboni', 'laila', 'lakshmi', 'lalita', 'lalitha', 'lata',
     'lavanya', 'laxmi', 'leela', 'lila', 'lilavati', 'lina', 'lochana', 'lucky', 'madhavi', 'madhu',
     'madhur', 'madhuri', 'mahinder', 'mala', 'malati', 'malini', 'mandeep', 'maninder', 'manisha',
     'manjeet', 'manju', 'manjula', 'manjusha', 'manpreet', 'mariyam', 'maryam', 'maya', 'meena',
     'meera', 'mina', 'minakshi', 'minali', 'mira', 'mitra', 'mohinder', 'mohini', 'mridula', 'mukta',
     'mumtaz', 'nalini', 'namrata', 'nandita', 'narinder', 'naseem', 'nasim', 'nasrin', 'navdeep',
     'navneet', 'nazia', 'neela', 'neelam', 'neelima', 'neha', 'nida', 'niketa', 'nikhila', 'nikita',
     'nikitha', 'nila', 'nilam', 'nilima', 'nilofar', 'nilofer', 'nilufar', 'nirmala', 'nirupama',
     'nisha', 'nishat', 'nithya', 'nitika', 'nitya', 'noor', 'nur', 'padma', 'padmini', 'pallabi',
     'pallavi', 'parminder', 'parvati', 'parveen', 'pooja', 'poornima', 'prachi', 'pratibha',
     'pratima', 'praveena', 'pravina', 'preethi', 'preeti', 'prema', 'pritha', 'priti', 'priya',
     'priyanka', 'puja', 'punita', 'purnima', 'pushpa', 'rachana', 'rachna', 'radha', 'radhika',
     'rahat', 'rajani', 'rajinder', 'rajkumari', 'rajni', 'rakhi']


indian = {
  'first_names_male': first_names_male,
  'first_names_female': first_names_female,
  'last_names': last_names
}